name: Release
on:
  push:
    branches:
      - main       
  
jobs:
  tag:
    name: Tag dev version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
 
      - name: Git tag with semver
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pre_release_branches: main
